//
// JsonModel.m
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
//

#import "LessonList.h"

@implementation LessonList

@synthesize Lessons;



+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
    id obj = [[LessonList alloc] initWithDictionary:dictionary];
    return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
    self=[super init];
    if(self)
    {
        
        NSArray* temp =  [dictionary objectForKey:@"lessons"];
        Lessons =  [[NSMutableArray alloc] init];
        for (NSDictionary *d in temp) {
            [Lessons addObject:[MLesson objectWithDictionary:d]];
        }
    }
    return self;
}


@end


@implementation MLesson

@synthesize Lesson_name;
@synthesize Lesson_id;
@synthesize Lesson_URL;


+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
    id obj = [[MLesson alloc] initWithDictionary:dictionary];
    return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
    self=[super init];
    if(self)
    {
        Lesson_name = [dictionary objectForKey:@"lesson_name"];
        Lesson_id = [dictionary objectForKey:@"lesson_id"];
        Lesson_URL = [dictionary objectForKey:@"lesson_url"];
    }
    return self;
}


@end

//JsonModel.m End
