//
// JsonModel.m
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
//

#import "QuizList.h"



@implementation QuizList

@synthesize Quizes;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
    id obj = [[QuizList alloc] initWithDictionary:dictionary];
    return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
    self=[super init];
    if(self)
    {
        
        NSArray* temp =  [dictionary objectForKey:@"quizes"];
        Quizes =  [[NSMutableArray alloc] init];
        for (NSDictionary *d in temp) {
            [Quizes addObject:[MQuize objectWithDictionary:d]];
        }
    }
    return self;
}


@end


@implementation MQuestion

@synthesize Question;
@synthesize Options;
@synthesize Correct_answer;


+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
    id obj = [[MQuestion alloc] initWithDictionary:dictionary];
    return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
    self=[super init];
    if(self)
    {
        Question = [dictionary objectForKey:@"question"];
        
        NSArray* temp =  [dictionary objectForKey:@"options"];
        Options =  [[NSMutableArray alloc] init];
        for (NSDictionary *d in temp) {
            [Options addObject:d];
        }
        Correct_answer = [dictionary objectForKey:@"correct_answer"];
    }
    return self;
}


@end


@implementation MQuize

@synthesize Quiz_name;
@synthesize Questions;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
    id obj = [[MQuize alloc] initWithDictionary:dictionary];
    return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
    self=[super init];
    if(self)
    {
        Quiz_name = [dictionary objectForKey:@"quiz_name"];
        
        NSArray* temp =  [dictionary objectForKey:@"questions"];
        Questions =  [[NSMutableArray alloc] init];
        for (NSDictionary *d in temp) {
            [Questions addObject:[MQuestion objectWithDictionary:d]];
        }
    }
    return self;
}


@end
